# .github/config.yml

welcome:
  # First-time contributor
  pr-message: >
    👋 Welcome to the project, and thanks for your first PR to `ci-template`!  
    Please take a moment to review our [contributing guide](https://github.com/hashmap-kz/ci-template/blob/master/CONTRIBUTING.md) — it includes all the basics to help you make great contributions.

  # Returning contributors
  pr-message-comment: >
    🎉 Thanks again for your contribution!  
    If you haven't already, feel free to revisit our [CONTRIBUTING.md](https://github.com/hashmap-kz/ci-template/blob/master/CONTRIBUTING.md) to stay in sync with project standards.
