name: Docker Image CI

on:
  push:

jobs:
  build_images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]
        role: [primary, standby]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers for pg-${{ matrix.role }}
        uses: actions/cache@v4
        with:
          path: /tmp/.pg-${{ matrix.role }}-${{ matrix.pg_major }}
          key: pg-${{ matrix.role }}-${{ matrix.pg_major }}
          restore-keys: |
            pg-${{ matrix.role }}-${{ matrix.pg_major }}-

      - name: Build 'pg-${{ matrix.role }}' image
        uses: docker/build-push-action@v6
        with:
          context: test/integration/environ
          file: test/integration/environ/dockerfiles/pg-${{ matrix.role }}/Dockerfile
          #platforms: linux/amd64,linux/arm64
          #push: ${{ github.ref_type == 'tag' }}
          tags: pgrwl/pg-${{ matrix.role }}-${{ matrix.pg_major }}
          build-args: |
            PG_MAJOR=${{ matrix.pg_major }}
          cache-from: type=local,src=/tmp/.pg-${{ matrix.role }}-${{ matrix.pg_major }}
          cache-to: type=local,dest=/tmp/.new-pg-${{ matrix.role }}-${{ matrix.pg_major }},mode=max
          # share between jobs (https://docs.docker.com/build/ci/github-actions/share-image-jobs/)
          outputs: type=docker,dest=${{ runner.temp }}/pg-${{ matrix.role }}-${{ matrix.pg_major }}.tar

      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      - name: Upload artifact 'pg-${{ matrix.role }}'
        uses: actions/upload-artifact@v4
        with:
          name: pg-${{ matrix.role }}-${{ matrix.pg_major }}
          path: ${{ runner.temp }}/pg-${{ matrix.role }}-${{ matrix.pg_major }}.tar

      - name: Move cache for pg-${{ matrix.role }}
        run: |
          rm -rf /tmp/.pg-${{ matrix.role }}-${{ matrix.pg_major }}
          mv /tmp/.new-pg-${{ matrix.role }}-${{ matrix.pg_major }} /tmp/.pg-${{ matrix.role }}-${{ matrix.pg_major }}

  test:
    name: Run integration tests (pg${{ matrix.pg_major }})
    runs-on: ubuntu-latest
    needs: [build_images]

    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Download both pg-primary and pg-standby artifacts for this PG_MAJOR
      # https://docs.docker.com/build/ci/github-actions/share-image-jobs/
      - name: Download pg images
        uses: actions/download-artifact@v4
        with:
          pattern: pg-*-${{ matrix.pg_major }}
          path: ${{ runner.temp }}
          merge-multiple: true

      - name: Load images
        run: |
          docker load --input ${{ runner.temp }}/pg-primary-${{ matrix.pg_major }}.tar
          docker load --input ${{ runner.temp }}/pg-standby-${{ matrix.pg_major }}.tar
          docker image ls -a

      # here you’d add your actual integration test steps
      # - name: Run tests
      #   run: |
      #     ...

# INPUTS:
#
# https://github.com/docker/build-push-action/blob/master/src/context.ts
#
# export interface Inputs {
#   'add-hosts': string[];
#   allow: string[];
#   annotations: string[];
#   attests: string[];
#   'build-args': string[];
#   'build-contexts': string[];
#   builder: string;
#   'cache-from': string[];
#   'cache-to': string[];
#   call: string;
#   'cgroup-parent': string;
#   context: string;
#   file: string;
#   labels: string[];
#   load: boolean;
#   network: string;
#   'no-cache': boolean;
#   'no-cache-filters': string[];
#   outputs: string[];
#   platforms: string[];
#   provenance: string;
#   pull: boolean;
#   push: boolean;
#   sbom: string;
#   secrets: string[];
#   'secret-envs': string[];
#   'secret-files': string[];
#   'shm-size': string;
#   ssh: string[];
#   tags: string[];
#   target: string;
#   ulimit: string[];
#   'github-token': string;
# }
