name: ci

on:
  push:

jobs:
  integ:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pg_major: [17, 18]

    env:
      PG_MAJOR: ${{ matrix.pg_major }}
      COMPOSE_FILE: test/integration/environ/docker-compose.yml

    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all images in parallel with cache
        run: |
          set -euo pipefail

          build_pg_primary() {
            docker buildx build \
              --file test/integration/environ/dockerfiles/pg-primary/Dockerfile \
              --build-arg PG_MAJOR="${PG_MAJOR}" \
              --tag pgrwl/pg-primary-${PG_MAJOR} \
              --cache-from type=gha,scope=pg-primary-${PG_MAJOR} \
              --cache-to   type=gha,scope=pg-primary-${PG_MAJOR},mode=max \
              --load \
              test/integration/environ
          }

          build_pg_standby() {
            docker buildx build \
              --file test/integration/environ/dockerfiles/pg-standby/Dockerfile \
              --build-arg PG_MAJOR="${PG_MAJOR}" \
              --tag pgrwl/pg-standby-${PG_MAJOR} \
              --cache-from type=gha,scope=pg-standby-${PG_MAJOR} \
              --cache-to   type=gha,scope=pg-standby-${PG_MAJOR},mode=max \
              --load \
              test/integration/environ
          }

          build_sshd() {
            docker buildx build \
              --file test/integration/environ/dockerfiles/sshd/Dockerfile \
              --tag pgrwl/sshd \
              --cache-from type=gha,scope=sshd \
              --cache-to   type=gha,scope=sshd,mode=max \
              --load \
              test/integration/environ
          }

          build_minio() {
            docker buildx build \
              --file test/integration/environ/dockerfiles/minio/Dockerfile \
              --tag pgrwl/minio \
              --cache-from type=gha,scope=minio \
              --cache-to   type=gha,scope=minio,mode=max \
              --load \
              test/integration/environ
          }

          build_minio_mc() {
            docker buildx build \
              --file test/integration/environ/dockerfiles/minio-mc/Dockerfile \
              --tag pgrwl/minio-mc \
              --cache-from type=gha,scope=minio-mc \
              --cache-to   type=gha,scope=minio-mc,mode=max \
              --load \
              test/integration/environ
          }

          # Run builds in parallel
          pids=()

          build_pg_primary &   pids+=($!)
          build_pg_standby &   pids+=($!)
          build_sshd &         pids+=($!)
          build_minio &        pids+=($!)
          build_minio_mc &     pids+=($!)

          # Wait for all to finish; if any fails, the step will fail
          for pid in "${pids[@]}"; do
            wait "$pid"
          done

      - name: Run tests
        run: |
          set -euo pipefail
          # don't rebuild in compose
          docker compose -f "${COMPOSE_FILE}" up -d --no-build
          docker ps
          # your test script here







#name: ci
#
#on:
#  push:
#
#jobs:
#  integ:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        pg_major: [17, 18]
#
#    env:
#      PG_MAJOR: ${{ matrix.pg_major }}
#      COMPOSE_FILE: test/integration/environ/docker-compose.yml
#
#    steps:
#      - uses: actions/checkout@v6
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      # Example: build pg-primary image with cache
#      - name: Build pg-primary image
#        run: |
#          set -euo pipefail
#          docker buildx build \
#            --file test/integration/environ/dockerfiles/pg-primary/Dockerfile \
#            --build-arg PG_MAJOR="${PG_MAJOR}" \
#            --tag pgrwl/pg-primary-${PG_MAJOR} \
#            --cache-from type=gha,scope=pg-primary-${PG_MAJOR} \
#            --cache-to   type=gha,scope=pg-primary-${PG_MAJOR},mode=max \
#            --load \
#            test/integration/environ
#
#      - name: Build pg-standby image
#        run: |
#          set -euo pipefail
#          docker buildx build \
#            --file test/integration/environ/dockerfiles/pg-standby/Dockerfile \
#            --build-arg PG_MAJOR="${PG_MAJOR}" \
#            --tag pgrwl/pg-standby-${PG_MAJOR} \
#            --cache-from type=gha,scope=pg-standby-${PG_MAJOR} \
#            --cache-to   type=gha,scope=pg-standby-${PG_MAJOR},mode=max \
#            --load \
#            test/integration/environ
#
#      - name: Build sshd image
#        run: |
#          set -euo pipefail
#          docker buildx build \
#            --file test/integration/environ/dockerfiles/sshd/Dockerfile \
#            --tag pgrwl/sshd \
#            --cache-from type=gha,scope=sshd \
#            --cache-to   type=gha,scope=sshd,mode=max \
#            --load \
#            test/integration/environ
#
#      - name: Build minio image
#        run: |
#          set -euo pipefail
#          docker buildx build \
#            --file test/integration/environ/dockerfiles/minio/Dockerfile \
#            --tag pgrwl/minio \
#            --cache-from type=gha,scope=minio \
#            --cache-to   type=gha,scope=minio,mode=max \
#            --load \
#            test/integration/environ
#
#      - name: Build minio-mc image
#        run: |
#          set -euo pipefail
#          docker buildx build \
#            --file test/integration/environ/dockerfiles/minio-mc/Dockerfile \
#            --tag pgrwl/minio-mc \
#            --cache-from type=gha,scope=minio-mc \
#            --cache-to   type=gha,scope=minio-mc,mode=max \
#            --load \
#            test/integration/environ
#
#      - name: Run tests
#        run: |
#          set -euo pipefail
#          # IMPORTANT: don't rebuild in compose
#          docker compose -f "${COMPOSE_FILE}" up -d --no-build
#          docker ps
#          # ... your exec test script, etc
#
