name: ci

on:
  push:

env:
  CACHE_FOLDER: docker-cache
  COMPOSE_FILE: "test/integration/environ/docker-compose.yml"

jobs:
  build_images:
    name: build ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: pg-primary
            file: test/integration/environ/dockerfiles/pg-primary/Dockerfile
            tag: prgwl/pg-primary-17:latest
            tarball: pg-primary-17.tar
          - name: pg-standby
            file: test/integration/environ/dockerfiles/pg-standby/Dockerfile
            tag: prgwl/pg-standby-17:latest
            tarball: pg-standby-17.tar

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image cache key
        id: cache-key
        run: |
          KEY="docker-images-${{ matrix.image.name }}-${{ hashFiles(
            'go.mod',
            'test/integration/environ/docker-compose.yml',
            'test/integration/environ/dockerfiles/**',
            'test/integration/environ/files/**',
            'test/integration/environ/scripts/**',
            '.github/workflows/integration.yml'
          ) }}"
          echo "value=${KEY}" >> "$GITHUB_OUTPUT"

      - name: Build ${{ matrix.image.name }}
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.image.file }}
          context: test/integration/environ
          tags: ${{ matrix.image.tag }}
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save images into tarballs
        run: |
          set -euo pipefail
          mkdir -p ${{ env.CACHE_FOLDER }}
          docker save ${{ matrix.image.tag }} | gzip > "${{ env.CACHE_FOLDER }}/${{ matrix.image.tarball }}"

      - name: Cache Docker images
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CACHE_FOLDER }}/${{ matrix.image.tarball }}
          key: ${{ steps.cache-key.outputs.value }}

      - name: Check cache
        run: |
          ls -lah ${{ env.CACHE_FOLDER }}
          docker images -a

#jobs:
#  build_images:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v6
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          file: test/integration/environ/dockerfiles/pg-primary/Dockerfile
#          context: test/integration/environ
#          tags: prgwl/pg-primary-17:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    needs: [build_images]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v6
#
#      - name: Load images
#        run: |
#          docker image ls -a
