---
name: CI

on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    branches:
      - master
      - "release/**"

jobs:
  ci_job:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: make test
      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"
      - name: Ensure go.mod is already tidied
        run: go mod tidy && git diff --exit-code

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     install-only: true
      #
      # - name: Check goreleaser
      #   run: make snapshot
