---
name: Integration Tests

on:
  push:
    branches:
      - "master"
      - "release/**"
  pull_request:
    branches:
      - "master"
      - "release/**"

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ github.ref }}
            buildx-

      - name: Build images with Buildx (cache aware)
        working-directory: test/integration/environ
        run: |
          (cd ../../../ && make build && mv bin test/integration/environ)
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag test/minio \
            --load \
            -f Dockerfile_minio .
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag test/pg \
            --load \
            -f Dockerfile_pg .
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag test/pg17 \
            --load \
            -f Dockerfile_pg17 .
          docker buildx build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --tag test/sshd \
            --load \
            -f Dockerfile_sshd .

      - name: Build and Start Test Environment
        working-directory: test/integration/environ
        run: |
          make restart
          make ps

      - name: Move cache
        run: |
          mkdir -p /tmp/.buildx-cache
          cp -r /tmp/.buildx-cache/. /tmp/.buildx-cache-new
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
