---
name: Integration Tests

on:
  push:
    branches:
      - "master"
      - "release/**"
  pull_request:
    branches:
      - "master"
      - "release/**"

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Restore Docker Cache
        uses: actions/cache@v4
        id: docker-cache
        with:
          path: /usr/bin/docker
          key: ${{ runner.os }}-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Test Environment
        working-directory: test/integration/environ
        run: |
          make restart
          make ps

      - name: Save Docker Build Cache
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/.buildx-cache
          cp -r /tmp/.buildx-cache/. /tmp/.buildx-cache-new
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
