name: Integration Tests

on:
  push:
    branches:
      - "master"
      - "release/**"
  pull_request:
    branches:
      - "master"
      - "release/**"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/integration/environ

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build Go binaries and move to integration directory
        run: echo "${PWD}" && (cd ../../../ && make build && mv bin test/integration/environ)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker layer cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ github.ref }}
            buildx-

#      - name: Build app image with cache
#        uses: docker/build-push-action@v5
#        with:
#          context: ./test/integration/environ
#          file: ./test/integration/environ/Dockerfile_pg
#          tags: pgrwl:pg
#          load: true
#          cache-from: type=local,src=/tmp/.buildx-cache
#          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build db image with cache
        uses: docker/build-push-action@v5
        with:
          context: ./test/integration/environ
          file: ./test/integration/environ/Dockerfile_sshd
          tags: pgrwl:minio
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run docker-compose
        run: |
          docker compose up -d --build
          docker compose ps
          docker images

      #      - name: Run integration tests
      #        run: go test ./test/integration/environ -v

      - name: Shut down containers
        if: always()
        run: docker compose down -v
