---
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      #      - name: Github Docker Login
      #        uses: docker/login-action@v3
      #        with:
      #          registry: quay.io
      #          username: ${{ secrets.DOCKER_USERNAME }}
      #          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HM_GITHUB_TOKEN }}

#  chart-release:
#    needs: goreleaser # wait until binaries are built & tag pushed
#
#    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
#    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
#    permissions:
#      contents: write
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#
#      - name: Run chart-releaser
#        uses: helm/chart-releaser-action@v1.7.0
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
