name: Release Impact on PR

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-impact:
    name: Generate Release Impact Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine previous tag
        id: prevtag
        run: |
          git fetch --tags
          PREV_TAG=$(git tag --sort=-version:refname | head -n2 | tail -n1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - uses: hashmap-kz/relimpact-action@main
        with:
          old-ref: ${{ steps.prevtag.outputs.prev_tag }}
          new-ref: HEAD
          output: release-impact.md

      - name: Upload Release Impact Report
        uses: actions/upload-artifact@v4
        with:
          name: release-impact
          path: release-impact.md

      - name: Post to PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: release-impact.md
